---
name: "CI"
on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  ################################
  # Run GH Super Linter          #
  ################################  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base with super-lint
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_BASH: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  ################################
  # Run NPM scripts              #
  ################################  
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v1      
      - run: |
          npm install
          npm run lint
          npm run test
          npm run build


  ################################
  # Build & publish              #
  ################################
  deploy: 
    name: Deploy to firebase
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
       - uses: actions/checkout@v2
      - run: |
          npm install
          npm run deploy
