---
name: "CI/CD"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ################################
  # Run GH Super Linter          #
  ################################
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base with super-lint
        uses: github/super-linter@latest
        env:
          VALIDATE_BASH: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ################################
  # Run NPM scripts              #
  ################################
  build_and_test:
    name: Build and Test
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm run build

  ################################
  # Build & publish              #
  ################################
  deploy:
    name: Deploy to Firebase
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        id: branch_name
        run: >
          echo "##[set-output name=channel_id;]$(

            if [[ ${GITHUB_REF_NAME} == "master" ]];
              then echo "live";
            else echo "${GITHUB_REF_NAME}";
            fi
          )"

      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADVANCEDWEBASSIGNMENT }}"
          channelId: ${{steps.branch_name.outputs.channel_id}}
          projectId: advancedwebassignment
